# JudgementDay Configuration
#
# This file contains the main configuration for the JudgementDay plugin.
# For punishment types and reasons, see punishments.yml
# For messages, see messages.yml

# Debug mode - enables additional logging
debug: false

# Storage configuration
storage:
  # Storage type: yaml or mysql
  type: yaml

  # MySQL/MariaDB configuration (if type is mysql)
  mysql:
    host: localhost
    port: 3306
    database: minecraft
    username: root
    password: password
    table-prefix: jd_

  # Data cleanup settings
  cleanup-interval: 24 # Hours between automatic cleanup tasks (0 to disable)
  reports-days-to-keep: 30 # Number of days to keep processed reports (0 to keep forever)

# Discord integration
discord:
  enabled: false
  webhook-url: ""

  # Which events to send to Discord
  notifications:
    punishments: true
    revocations: true
    reports: true
    appeals: true

  # Embed colors (hex color codes)
  colors:
    warn: "#FFCC00"
    mute: "#FF9900"
    kick: "#FF66CC"
    ban: "#FF0000"
    revoke: "#00CC00"
    report: "#3399FF"
    appeal: "#9900CC"

# Report settings
reports:
  cooldown: 300 # Seconds between reports of the same player
  min-reason-length: 3
  max-reason-length: 100

# Appeal settings
appeals:
  max-per-day: 3 # Maximum number of appeals a player can submit per day
  ban-only: false # If true, only ban punishments can be appealed

# Input validation
validation:
  proof-links:
    enabled: true
    allowed-domains:
      - imgur.com
      - prnt.sc
      - gyazo.com
      - youtube.com
      - youtu.be
      - streamable.com
      - discord.com

# Integrations with other plugins
integrations:
  placeholder-api: true # Enable PlaceholderAPI support
  discord-srv: false # Enable DiscordSRV support