name: JudgementDay
version: 2.0.0
main: com.judgementday.judgementday
author: YourName
description: Sistema avançado de gerenciamento de punições e moderação para servidores
website: https://seu-site.com
api-version: 1.13
softdepend: [Vault]

commands:
  punish:
    description: Aplica uma punição a um jogador
    usage: /punish <player>
    aliases: [punir]
  revoke:
    description: Revoga uma punição existente
    usage: /revoke <id> [reason]
    aliases: [revogar]
  history:
    description: Mostra o histórico de punições de um jogador
    usage: /history <player>
    aliases: [historico]
  report:
    description: Reporta um jogador por comportamento inadequado
    usage: /report <player> <reason>
    aliases: [reportar]
  reports:
    description: Mostra a lista de reports pendentes
    usage: /reports
  appeal:
    description: Apela contra uma punição recebida
    usage: /appeal <punishment_id>
    aliases: [apelar]
  jdadmin:
    description: Comandos de administração do JudgementDay
    usage: /jdadmin [reload|reports|appeals|cleanup]
  check:
    description: Verifica as punições ativas de um jogador
    usage: /check <player>
    aliases: [verificar]

permissions:
  judgementday.*:
    description: Acesso a todos os comandos do JudgementDay
    children:
      judgementday.punish: true
      judgementday.revoke: true
      judgementday.history: true
      judgementday.history.others: true
      judgementday.report: true
      judgementday.reports: true
      judgementday.appeal: true
      judgementday.admin: true
      judgementday.check: true
      judgementday.check.others: true
      judgementday.staff: true
      judgementday.bypass.mute: true
  judgementday.punish:
    description: Permite aplicar punições
    default: op
  judgementday.revoke:
    description: Permite revogar punições
    default: op
  judgementday.history:
    description: Permite ver seu próprio histórico de punições
    default: true
  judgementday.history.others:
    description: Permite ver o histórico de punições de outros jogadores
    default: op
  judgementday.report:
    description: Permite reportar jogadores
    default: true
  judgementday.reports:
    description: Permite ver reports pendentes
    default: op
  judgementday.appeal:
    description: Permite apelar contra punições
    default: true
  judgementday.admin:
    description: Permite usar comandos de administração
    default: op
  judgementday.check:
    description: Permite verificar suas próprias punições ativas
    default: true
  judgementday.check.others:
    description: Permite verificar punições ativas de outros jogadores
    default: op
  judgementday.staff:
    description: Recebe notificações de staff
    default: op
  judgementday.bypass.mute:
    description: Permite falar mesmo quando silenciado
    default: op